In [2]:
# Lenh in 
print (5/8)

0.625


In [3]:
print (10+7)

17


In [4]:
#them ghi chu trong pyhton

#day la 1 ghi chu
print ("thao") # in ra thao

thao


In [5]:
# phep cong
print (10+5)

# phep tru 
print (10-2)

# phep nhan 
print (10 * 6)

# phep chia
print (10/6)

# phep luy thua
print (4 ** 2)

# phep lay du
print (3 % 2)


15
8
60
1.6666666666666667
16
1


Bài tập: An có 1000 USD gửi ngân hàng với lãi suất 10% mỗi năm. Hãy viết đoạn code để tính và in ra số tiền mà An nhận được sau 15 năm gửi ngân hàng:

In [6]:
print (1000 * ((1+0.1)**15))

4177.248169415656


Phần 2: Biến và kiểu dữ liệu

In [7]:
# gan gia tri 5 cho x
x = 5
print (x)

5


Bài tập:

Khởi tạo biến savings có giá trị bằng 1000
In ra giá trị của biến savings

In [8]:
savings = 1000
print (savings)

1000


In [9]:
savings = 1000
factor = 10/100
y = savings * (1+factor)** 15
print (y)


4177.248169415656


Kiểu dữ liệu
int : so nguyen
float: so thuc
str: xau ( chuoi); duoc khai bao boi: "" hoac ''
bool: nhan True hoac False

Bài tập:

Tạo một xâu ký tự desc với giá trị là "Data Science"
Tạo một biến boolean tên là profitable có giá trị True

In [10]:
desc = "Data Science"
profitable = True
print (desc)
print (type(desc))
print (profitable)
print (type(profitable))

Data Science
<class 'str'>
True
<class 'bool'>


Bài tập: In ra kiểu dữ liệu của các biến savings, factor, desc và profitable đã khai báo ở các mục trước.

In [11]:
print (type(savings))
print(type(factor))
print(type(desc))
print(type(profitable))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


Bài tập: Cho các biến và giá trị của nó trong đoạn code dưới đây. Công việc của bạn là:

Tính tích của savings và factor, lưu trữ giá trị vào biến year1.
Kiểu dữ liệu của biến year1 là gì? Hãy tự tìm đáp án bằng cách in nó ra.
Tính tổng của desc và desc rồi lưu kết quả vào biến doubledesc.
Sau đó, in ra giá trị của doubledesc. Kết quả có nằm trong dự đoán của bạn chứ?

In [12]:
year1 = savings * factor
print (type(year1))
doubledesc = desc + desc 
print (doubledesc)


<class 'float'>
Data ScienceData Science


Bài tập:

Hãy chạy đoạn code dưới đây, đọc hiểu lỗi mà trình biên dịch báo và tìm cách sửa code để khắc phục lỗi này.
Chuyển giá trị của pi_string sang số thực và gán giá trị đó cho biến pi_float.

In [13]:
# Khai báo biến savings và result
savings = 1000
result = 1000 * 1.10 ** 15

# Sửa lại lệnh in dưới đây cho đúng
print("Tôi gửi ngân hàng $" + str(savings) + ", sau 15 năm, bây giờ tôi đã có $" + str(result) + ". Tuyệt vời!")

# Khai báo pi_string
pi_string = "3.1415926"

# Chuyển pi_string sang float: pi_float
pi_float = float(pi_string)
print(pi_float)

Tôi gửi ngân hàng $1000, sau 15 năm, bây giờ tôi đã có $4177.248169415656. Tuyệt vời!
3.1415926


Phần 3: Danh sách
Danh sách (list) là một kiểu dữ liệu đặc biệt, là tổ hợp của các biến thuộc các kiểu dữ liệu khác nhau.

Bài tập: Bạn đo đạc diện tích các căn phòng trong nhà và lưu kết quả vào các biến ở đoạn code dưới đây. Yêu cầu:

Tạo 1 danh sách tên là areas chứa diện tích các phòng và khu vực trong nhà: hành lang (hall), phòng bếp (kit), phòng khách (liv), phòng ngủ (bed) và phòng tắm (bath) theo đúng thứ tự đó.
In ra giá trị của areas sử dụng hàm print().

In [14]:
hall = 11.25
kit = 10
liv = 8.5
bath = 6
areas = [hall, kit, liv, bath]
print(areas)

[11.25, 10, 8.5, 6]


Bài tập:

Thêm đầy đủ tên các phòng vào danh sách areas, mỗi tên phòng đều đứng ngay trước biến chứa diện tích của nó: "hallway" cho hall, "kitchen" cho kit, "bedroom" cho bed.
In ra giá trị của areas.

In [15]:
areas = ["hallway", hall, "kitchen", kit, "livingroom", liv, "bathroom", bath]
print(areas)

['hallway', 11.25, 'kitchen', 10, 'livingroom', 8.5, 'bathroom', 6]


 Danh sách cũng là 1 kiểu trong Python, 1 danh sách cũng có thể chứa 1 hoặc nhiều danh sách con trong nó

In [16]:
e1 = [1,2,3]
e2 = [4,5,6]
e3 = [7,8,9]
e = [e1, e2, e3]
print(e)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [17]:
house = [["hallway", hall], ["kitchen", kit], ["livingroom", liv], ["bathroom", bath]]
print(house)
print(type(house))

[['hallway', 11.25], ['kitchen', 10], ['livingroom', 8.5], ['bathroom', 6]]
<class 'list'>


Phần 4: Các thao tác truy cập danh sách
Phần tử thứ nhất có chỉ số là 0, phần tử thứ hai có chỉ số là 1,... Trong Python, chúng ta cũng có thể sử dụng chỉ số âm (phần tử cuối cùng trong danh sách có chỉ số là -1, phần tử gần cuối có chỉ số là -2)

Bài tập:

In ra phần tử thứ 2 của areas (11.25).
In ra phần tử cuối cùng của areas (9.5), hãy thử sử dụng chỉ số âm.
Tìm chỉ số của phần tử biểu diễn diện tích phòng khách và in ra giá trị của phần tử đó

In [18]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
print (areas[1])
print(areas[-1])
for i in range(len(areas)):
    if (areas[i] == "living room"):
        print(areas[i + 1])

11.25
9.5
20.0


In [19]:
x = ["a", "b", "c", "d"]
print(x[1] + x[3])

bd


In [20]:
eat_sleep_area = areas[3] + areas[7]
print (eat_sleep_area)

28.75


Trong Python, việc trích xuất nhiều phần tử liên tiếp của một danh sách là rất đơn giản. Ta sử dụng công thức sau:

mylist[start:end]
để trích từ danh sách mylist các phần tử có chỉ số từ start đến end-1 (phần tử có chỉ số end sẽ không được trích ra).

Bài tập:

Trích ra 6 phần tử đầu của danh sách areas để khởi tạo danh sách downstairs.
Trích ra 4 phần tử còn lại để khởi tạo danh sách upstairs

In [21]:
downstairs = areas[:6]
print(downstairs)
upstairs = areas[6:]
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


Đối với một danh sách chứa các phần tử là danh sách con, để truy cập vào phần tử của danh sách con, ta sẽ dùng nhiều cặp ngoặc vuông liên tiếp nhau. Hãy chạy thử đoạn code dưới đây và khám phá cách hoạt động của nó:


In [22]:
x = [[1,2,3],
     [4,5,6],
     [7,8,9]]
print(x[1][:])

[4, 5, 6]


Phần 5: Các thao tác chỉnh sửa danh sách

Bài tập:

Bạn phát hiện ra mình đo nhầm diện tích của phòng tắm. Diện tích đúng là 10.50 thay vì 9.50. Hãy sửa lại nó ở trong danh sách areas.
Hãy sửa lại tên của phòng khách thành "chill zone".

In [23]:
areas[-1] = 10.5
areas[-6] = "chill zone"
print (areas[:])

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


Để mở rộng một danh sách, ta sử dụng toán tử + trên 2 danh sách.

Bài tập: Bạn vừa trúng Vietlot, bạn quyết định đầu tư để xây thêm bể bơi ("poolhouse") và gara ô tô ("garage") cho nhà của mình. Hãy thêm dữ kiện ["poolhouse", 24.5] vào cuối danh sách areas để tạo danh sách areas_1. Sau đó hãy thêm xâu "garage" và số thực 15.45 vào cuối của areas_1, tạo danh sách mới tên là areas_2.

In [24]:
x = ["poolhouse", 24.5]
y = ["garage", 15.45]
areas_1 = areas + x
areas_2 = areas_1 + y
print (areas_1)
print (areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


Để xóa phần tử khỏi danh sách, ta dùng hàm del().

Bài tập: Số tiền trúng Vietlot bạn đã dùng một phần vào việc khao bạn bè, gia đình nên bạn không còn đủ tiền xây bể bơi nữa. Bạn cần bỏ dữ kiện về bể bơi ("poolhouse" và diện tích của nó) ra khỏi danh sách areas. Hãy dùng 2 lệnh del() để thực hiện việc này.

In [26]:
del(areas_2[-3])
del(areas_2[-3])
print (areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'garage', 15.45]


Trong Python, để sao chép các phần tử của một danh sách sang một danh sách khác, ta có thể dùng hàm list() hoặc toán tử [:]

Bài tập: Sửa lại cách sao chép danh sách areas ở đoạn code dưới đây sao cho khi thay đổi areas_copy thì areas không bị thay đổi.

In [28]:
# khởi tạo areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# tạo areas_copy
areas_copy = list(areas)

# thay đổi areas_copy
areas_copy[0] = 5.0

# in ra areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


Phần 6: Hàm

Bài tập:

Sử dụng hàm print() và hàm type() để in ra kiểu dữ liệu của biến var1
Hàm len() dùng để tính số lượng phần tử của một danh sách. Hãy kết hợp với hàm print() để in ra số lượng phần tử của var1.
Chuyển biến var2 sang kiểu số nguyên và lưu vào biến out2.

In [29]:
# khởi tạo
var1 = [1, 2, 3, 4]
var2 = True
print(type(var1))
print(len(var1))
out2 = int(var2)
print(out2)

<class 'list'>
4
1
True


Các hàm xây dựng sẵn trong Python đều có hướng dẫn sử dụng. Để xem hướng dẫn này, ta sử dụng hàm help().

In [30]:
help(min)

Help on built-in function min in module builtins:

min(...)
    min(iterable, *[, default=obj, key=func]) -> value
    min(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its smallest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the smallest argument.



In [31]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.

    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [32]:
# khởi tạo
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# ghép first và second vào danh sách full
full = first + second 

# sắp xếp lại full theo thứ tự giảm dần, lưu vào biến full_sorted
full_sorted = sorted(full, reverse=True)

# in ra full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


Phần 7: Phương thức
Trong Python, tất cả các biến chúng ta tạo ra đều là các đối tượng (object) và chúng thuộc các kiểu (type) khác nhau.

Trong các đối tượng này đều có các hàm đã được xây dựng sẵn, ta gọi đó là các phương thức (method). Để sử dụng phương thức của một đối tượng, ta dùng toán tử dấu chấm (.) với công thức sau:
đối_tượng.phương_thức()

In [33]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(

Bài tập: Ở bài tập này, một biến room đã được tạo sẵn cho bạn.

Sử dụng phương thức upper() tạo ra xâu chữ hoa từ xâu room, lưu kết quả vào biến room_up. In ra room và room_up để xem kết quả.
Sử dụng phương thức count() trên đối tượng room để đếm số lượng chữ cái "o" trong xâu room này. In ra kết quả tìm được.

In [36]:
# tạo xâu room
room = "poolhouse"

# sử dụng hàm upper() trên room, lưu kết quả vào room_up
room_up = room.upper()

# in ra room và room_up
print(room)
print(room_up)

# in ra số lượng chữ cái o trong xâu room
print(room.count('o'))

poolhouse
POOLHOUSE
3


In [37]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [43]:
# khởi tạo
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# in ra chỉ số (index) của phần tử có giá trị 20.0
print(areas.index(20.0))

# in ra số lần xuất hiện của 14.5 trong areas, sử dụng phương thức count()
print(areas.count(9.5))

2
1


Bài tập:

Thêm dữ liệu diện tích của bể bơi (24.5) và gara (15.45) vào cuối danh sách areas đã được tạo sẵn.
Đảo ngược lại thứ tự của các phần tử trong areas.

In [44]:
# khởi tạo
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

areas.append(24.5)
areas.append(15.45)
areas.reverse()
print(areas)

[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


Phần 8: Sử dụng gói (Packages)
Ta cũng có thể sử dụng 1 tên thay thế cho những gói mà ta nhập vào đoạn code của mình bằng cách dùng từ khóa as:
import numpy as np
arr = np.array([1,2])

Trong gói math của Python có hằng số pi, để sử dụng hằng số này ta gọi math.pi. Hãy sử dụng hằng số này để tính diện tích và chu vi của một hình tròn có bán kính r. Công thức tính chu vi C và diện tích S của hình tròn:

C=2πr 
S=πr2

In [45]:
# định nghĩa bán kính r
r = 0.43

# import gói "math"
import math as m

# tính chu vi C
C = 0
C = 2 * m.pi * r
# tính diện tích S
S = 0
S = m.pi * (r**2)
# in kết quả
print("Chu vi: " + str(C))
print("Diện tích: " + str(S))

Chu vi: 2.701769682087222
Diện tích: 0.5808804816487527


Khi sử dụng import math, ta đã nhập toàn bộ tài nguyên của gói math. Tuy nhiên, thông thường ta chỉ sử dụng một số tài nguyên của các gói này, để nhập một phần trong gói, ta sử dụng từ khóa from ... import .... Ví dụ, với bài tập trước, ta chỉ sử dụng số pi trong gói math, do đó ta chỉ cần nhập như sau:

from math import pi

Bài tập: Giả sử Mặt Trăng quay quanh Trái Đất của chúng ta với quỹ đạo là một đường tròn có bán kính r được định nghĩa trong đoạn code dưới đây. Tính quãng đường mà Mặt Trăng di chuyển sau khi nó quay được một góc là  12o . Bạn có thể sử dụng công thức sau để tính quãng đường di chuyển của Mặt Trăng:  r∗ϕ  với  ϕ  là độ lớn của góc tính bằng radian. Hãy sử dụng hàm radians() trong gói math để chuyển độ lớn của góc sang radian.

In [46]:
# định nghĩa bán kính r
r = 192500

# nhập hàm radians trong gói math
from math import radians as ra

# dist = quãng đường Mặt Trăng di chuyển sau khi quay được 12 độ
dist = r * ra(120)

# in ra giá trị dist
print(dist)

403171.0572106901



Phần 9: Numpy